#5481 update to ipywidgets v7
twosigma/beakerx pull request #5873
Opened 2017-08-22 12:43 UTC by michalgce

2017-08-22 15:54 UTC, scottdraves commented
let's wait until v7 appears in conda

2017-08-23 14:34 UTC, scottdraves commented
![screen shot 2017-08-23 at 10 33 57 am](https://user-images.githubusercontent.com/963093/29621426-a8aad978-87ee-11e7-8d17-283fd4bbd7e9.png)
EasyForm not syncing its values back to Kernel

2017-08-23 14:39 UTC, scottdraves commented
i can safely switch on and off this branch by using
```
conda install -c conda-forge ipywidgets=7.0.0
```
and
```
conda install -c conda-forge widgetsnbextension=2.0.0 ipywidgets=6.0.0
```

2017-08-29 10:23 UTC, MariuszJurowicz requested changes

2017-08-29 10:23 UTC, mjurowicz-xsolve commented on beakerx/js/webpack.config.js
> +    externals: ['@jupyter-widgets/controls', '@jupyter-widgets/base', '@jupyter-widgets/base'],
`@jupyter-widgets/base` duplicated

2017-08-29 10:23 UTC, mjurowicz-xsolve commented on kernel/base/src/main/java/com/twosigma/beakerx/easyform/EasyFormComponent.java
> +        } else if (stateMap.containsKey("index")) {
Maybe this whole `if` statement could be simplified a little

2017-08-29 10:23 UTC, mjurowicz-xsolve commented on kernel/base/src/main/java/com/twosigma/beakerx/widgets/selections/SelectionWidget.java
> +    return "@jupyter-widgets/controls";
Is this change necessary while in other examples we are using `jupyter-js-widgets` ?

2017-08-29 14:02 UTC, MariuszJurowicz approved these changes

2017-08-29 16:55 UTC, merged